# https://docs.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

updates:
  - commit-message:
      include: "scope"
      prefix: "composer"
    directory: "/"
    labels:
      - "dependency"
    open-pull-requests-limit: 5
    package-ecosystem: "composer"
    schedule:
      interval: "daily"
    versioning-strategy: "increase"

  - commit-message:
      include: "scope"
      prefix: "tools"
    directory: "/tools/*/"
    labels:
      - "dependency"
    open-pull-requests-limit: 5
    package-ecosystem: "composer"
    schedule:
      interval: "daily"
      time: "15:00"
    versioning-strategy: "increase"