version: '3.8'

services:
  app:
    image: webdevops/php-nginx-dev:7.4
    user: application
    working_dir: /app
    environment:
      WEB_DOCUMENT_ROOT: /app/public
      WEB_DOCUMENT_INDEX: index.php
      XDEBUG_MODE: coverage
      PHP_MEMORY_LIMIT: 128M
    volumes:
      - .:/app
    ports:
      - "80:80"