#index:
#    path: /
#    controller: App\Controller\DefaultController::index

badge_composerlock:
  path: /{repository}/composerlock
  controller: App\Controller\ComposerLockController
  requirements:
    repository: '[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+?'

badge_total_downloads:
  path: /{repository}/downloads
  controller: App\Controller\TotalDownloadsController
  requirements:
    repository: '[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+?'

badge_total_downloads_alternative:
  path: /{repository}/d/total
  controller: App\Controller\TotalDownloadsController
  requirements:
    repository: '[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+?'

badge_monthly_downloads:
  path: /{repository}/d/monthly
  controller: App\Controller\MonthlyDownloadsController
  requirements:
    repository: '[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+?'